---
- name: Service Testing
  hosts: docker
  become: yes
  become_user: root
  become_method: sudo
#  gather_facts: no
  tasks:

#  - name: Stop
#    ansible.builtin.service:
#      name: sqlserv
#      state: stopped

  - name: Install Apache2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Debian'

  - name: Update all
    apt:
      name: "*"
      state: latest

#  - name: Start httpd
#    service: 
#      name=httpd 
#      state=started

  - name: Restart Apache2
    ansible.builtin.service:
      name: apache2
      state: restarted
    ignore_errors: yes
