---
- name: Praticing
  hosts: all
  tasks:

  - name: OS ->
    debug: 
      msg: "OS is {{ansible_distribution}}"

  - name: OS -> Major version
    debug:
      msg: "Major version is {{ansible_distribution_major_version}}" 

  - name: OS -> Version
    debug:
      msg: "Version is {{ansible_distribution_version}}"

  - name: Testing
    debug: 
      msg: "{{ansible_os_family}}"

  - name: Inventory hostname
    debug:
      msg="Name in inventory is {{inventory_hostname}}"

  - name: Apache Only
    debug:
      msg: "Hello from an Apache server"
    when: ansible_distribution == 'Debian'
    
  - name: Python Version
    debug:
      msg: "Python is {{ansible_python_version}}"

  - name: DNS
    debug:
      msg: "DNS is {{ansible_dns}}"

  - name: IPv4
    debug: 
      msg: "IPv4 is {{ansible_all_ipv4_addresses}}"
    ignore_errors: yes

- name: Praticing2
  hosts: all
  tasks:

  - name: LSB
    debug:
      msg: "{{ansible_lsb}}"
